### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by wemersonjanuario** [bmoeskau/Extensible#86]
Is this project abandoned? Too many pull request, and no release for Ext JS 5 or 6

**Comment by bmoeskau** [comment]
Not abandoned, no, but extremely far behind where it needs to be right now for sure. I have some updates queued up, it's just a matter of finding some time to make it happen.

**Comment by nsams** [comment]
*please* :)

**Comment by wemersonjanuario** [comment]
It would be Nice to see updates.
Em 16/04/2015 02:44, "Niko Sams" <notifications@github.com> escreveu:

**Comment by wemersonjanuario** [comment]
updatessssssssssssssssssss!

**Comment by diego3** [comment]
nice project, it not deserve to be abandoned!

**Comment by cndreiter** [comment]
really cool project. please update.

**Comment by bmoeskau** [comment]
Not abandoned. Just not super active lately, but I just made some updates so I guess I can close this for now.
