### ISSUE TITLE
Support Extjs5.1.1

### ISSUE THREAD

**Issue by JayAhuja555** [bmoeskau/Extensible#87]
Hello 
Does Latest version support Extjs 5.1.1?

**Comment by bmoeskau** [comment]
Not at the moment but it's in the works

**Comment by nsams** [comment]
that's good news! You might even consider ExtJs 6....

**Comment by cndreiter** [comment]
+1

**Comment by JayAhuja555** [comment]
I have one query, 
how we can refresh the view of calendar panel ? when we reload the store ?

**Comment by bmoeskau** [comment]
`calendarPanel.getActiveView().refresh()`? For more help on this you might consider posting to the user forums http://ext.ensible.com/forum/

**Comment by JayAhuja555** [comment]
Thanks alot @bmoeskau .
Is there any config in which we can allow user to change the month view between 2 dates for Example 
i want allow user to change month view between 2014 to 2016 year only ?
